// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace NetCoreHomework.Models
{
    public partial class CourseInstructor
    {
        public int CourseID { get; set; }
        public int InstructorID { get; set; }

        public virtual Course Course { get; set; }
        public virtual Person Instructor { get; set; }
    }
}