// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace NetCoreHomework.Models
{
    public partial class vwCourseStudents
    {
        public int? DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public int CourseID { get; set; }
        public string CourseTitle { get; set; }
        public int? StudentID { get; set; }
        public string StudentName { get; set; }
    }
}