// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace NetCoreHomework.Models
{
    public partial class vwCourseStudentCount
    {
        public int? DepartmentID { get; set; }
        public string Name { get; set; }
        public int CourseID { get; set; }
        public string Title { get; set; }
        public int? StudentCount { get; set; }
    }
}