// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace NetCoreHomework.Models
{
    public partial class vwDepartmentCourseCount
    {
        public int DepartmentID { get; set; }
        public string Name { get; set; }
        public int? CourseCount { get; set; }
    }
}